import React from 'react';
import PageHero from '../components/PageHero';
import CtaSection from '../components/CtaSection';
import { BrainCircuit, Cpu, RefreshCw, Workflow } from 'lucide-react';

const GenerativeAI = () => {
  return (
    <div>
      <PageHero 
        title="Generative AI in Engineering" 
        subtitle="Augmenting Human Ingenuity with Machine Intelligence for Rapid Product Development"
        backgroundImage="https://images.unsplash.com/photo-1620712948633-281565bf73ab?q=80&w=2938&auto=format&fit=crop"
      />

      <section className="py-20 bg-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
           <div className="text-center max-w-4xl mx-auto mb-16">
              <h2 className="text-3xl font-bold text-gray-900 mb-6">The Next Era of Industrial Design</h2>
              <p className="text-lg text-gray-600">
                At AECS, we integrate Generative AI into our CAD and FEA pipelines. Instead of manually drawing a single solution, our engineers input constraints (weight, load, material), and the AI algorithms return hundreds of optimized geometric variations.
              </p>
           </div>
           
           <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
              {[
                { icon: <BrainCircuit />, title: "Generative Design", desc: "Creating highly complex, organic structures that reduce weight by up to 40% while maintaining structural integrity." },
                { icon: <RefreshCw />, title: "Automated FEA Iteration", desc: "AI-driven mesh optimization and solver predictions that reduce simulation times from days to hours." },
                { icon: <Workflow />, title: "Digital Twins", desc: "Creating real-time virtual representations of physical assets to predict maintenance and operational efficiency." },
                { icon: <Cpu />, title: "Supply Chain AI", desc: "Predictive algorithms that optimize BOM (Bill of Materials) sourcing and manufacturing line schedules." }
              ].map((item, idx) => (
                <div key={idx} className="bg-brand-dark p-8 rounded-xl text-white shadow-lg border border-gray-800">
                   <div className="text-brand-secondary mb-6">{item.icon && React.cloneElement(item.icon, { className: 'w-10 h-10' })}</div>
                   <h3 className="font-bold text-xl mb-3">{item.title}</h3>
                   <p className="text-gray-400 text-sm">{item.desc}</p>
                </div>
              ))}
           </div>
        </div>
      </section>

      <section className="py-20 bg-gray-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="lg:flex lg:items-center lg:gap-16">
            <div className="lg:w-1/2 mb-10 lg:mb-0">
               <img src="https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=2942&auto=format&fit=crop" alt="AI Generated Part" className="rounded-xl shadow-xl w-full" />
            </div>
            <div className="lg:w-1/2">
               <h2 className="text-3xl font-bold text-gray-900 mb-6">Additive Manufacturing unlocks AI geometries.</h2>
               <p className="text-gray-600 mb-6">
                 Historical manufacturing methods like CNC machining often couldn't produce the complex, "alien-looking" structures generated by AI. Today, combined with our advanced 3D printing and rapid prototyping capabilities, we can bring these ultra-efficient, AI-generated shapes into reality for aerospace and automotive clients.
               </p>
               <button className="btn-primary">View Case Studies</button>
            </div>
          </div>
        </div>
      </section>

      {/* Academic Partners & Research Section */}
      <section className="py-20 bg-white border-t border-gray-100">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
           <div className="mb-16 text-center">
              <h2 className="text-3xl font-bold text-gray-900 mb-4">Academic Partners & Research</h2>
              <p className="text-gray-600 max-w-2xl mx-auto">We collaborate with premier engineering institutions to provide specialized Project Based Learning (PBL) for AI programs and courses.</p>
           </div>
           
           <div className="grid grid-cols-1 md:grid-cols-2 gap-8 max-w-4xl mx-auto">
              <div className="bg-gray-50 p-8 rounded-2xl border border-gray-100 flex flex-col items-center text-center group hover:shadow-md transition-all duration-300">
                 <div className="h-32 flex items-center justify-center mb-6">
                    <img 
                      src="https://www.svnit.ac.in/images/logo.png" 
                      alt="NIT Surat Logo" 
                      className="max-h-full w-auto transition-all duration-300"
                    />
                 </div>
                 <h3 className="text-xl font-bold text-gray-900 mb-2">Sardar Vallabhbhai National Institute of Technology (SVNIT), Surat</h3>
                 <p className="text-gray-500 text-sm italic">Deemed University under Ministry of Education, Govt. of India</p>
              </div>

              <div className="bg-gray-50 p-8 rounded-2xl border border-gray-100 flex flex-col items-center text-center group hover:shadow-md transition-all duration-300">
                 <div className="h-32 flex items-center justify-center mb-6">
                    <img 
                      src="https://ktu.edu.in/static/media/logo_header.77120c0967a09b766cdf.png" 
                      alt="KTU Logo" 
                      className="max-h-full w-auto transition-all duration-300"
                    />
                 </div>
                 <h3 className="text-xl font-bold text-gray-900 mb-2">APJ Abdul Kalam Technological University (KTU), Kerala</h3>
                 <p className="text-gray-500 text-sm italic">Kerala Technological University</p>
              </div>
           </div>
        </div>
      </section>

      <CtaSection title="Ready to Optimize Your Parts?" subtitle="Let's run your existing geometries through our Generative AI pipeline and see how much weight and cost we can save." />
    </div>
  );
};

export default GenerativeAI;
